version: "3.9"
 
services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5438:5432"             # host:container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}        # superuser (admin)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-quizmaster_entreprise}            # default DB
      PGDATA: /var/lib/postgresql/data/pgdata_quizmaster_entreprise
    volumes:
      - pgdata:/var/lib/postgresql/data           # bind mount on host
      - ./back/tables.sql:/docker-entrypoint-initdb.d/tables.sql:ro     # SQL tables initialization
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-quizmaster_entreprise}"]
      interval: 10s
      timeout: 5s
      retries: 5
 
volumes:
  pgdata: 

networks:
  default:
    name: local-postgres