version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quizmaster
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./back
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./back:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/quizmaster
    depends_on:
      - db
    ports:
      - "8000:8000"

  front:
    build: ./front
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata: 